### ISSUE TITLE
Do not remove attribution for the chatchart cog

### ISSUE THREAD

**Issue by aikaterna** [TheBestEagleEye/EagleCogs#1]
You should put my name back in your info.json for chatchart since it's my cog. Respect the MIT license on the original.

**Comment by TheBestEagleEye** [comment]
I'm sorry for doing that and I've restored your credit to the info.json and your notes back to chatchart.py. I copy pasted the code and removed your notes because I thought it was unnecessary but I shouldn't have done that. I've never used GitHub for anything really before. Would it be better if I forked your repo and made any edits there? I just had some plans of making some of my own simple cogs and I wanted to edit one of yours so I added it here without thinking about it.

**Comment by TheBestEagleEye** [comment]
Thank you. I will move the chatchart cog over to a fork.
